bible_search_terms = [
    'Genesis', 'Gen',
    'Exodus',  'Exod',
    'Leviticus', 'Lev',
    'Numbers', 'Num',
    'Deuteronomy', 'Deut',
    'Joshua', 'Josh',
    'Judges', 'Judg',
    'Ruth',
    '1 Samuel', '1 Sam', '1Samuel', '1Sam',
    '2 Samuel', '2 Sam', '2Samuel', '2Sam',
    '1 Kings', '1 Kgs', '1Kings', '1Kgs',
    '2 Kings', '2 Kgs', '2Kings', '2Kgs',
    '1 Chronicles', '1 Chr', '1Chronicles', '1Chr',
    '2 Chronicles', '2 Chr', '2Chronicles', '2Chr',
    'Ezra',
    'Nehemiah', 'Neh',
    'Esther',  'Esth',
    'Job',
    'Psalms', 'Psalm', 'Ps',
    'Proverbs',  'Prov',
    'Ecclesiastes', 'Eccl',
    'Song of Solomon', 'Song', 'Canticle of Canticles', 'Canticles', 'Cant',
    'Isaiah', 'Isa',
    'Jeremiah', 'Jer',
    'Lamentations', 'Lam',
    'Ezekiel', 'Ezek',
    'Daniel',  'Dan',
    'Hosea',   'Hos',
    'Joel',
    'Amos',
    'Obadiah', 'Obad',
    'Jonah',
    'Micah',    'Mic',
    'Nahum',    'Nah',
    'Habakkuk', 'Hab',
    'Zephaniah', 'Zeph',
    'Haggai',   'Hag',
    'Zechariah', 'Zech',
    'Malachi', 'Mal',
    'Matthew', 'Matt',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans', 'Rom',
    '1 Corinthians', '1 Cor', '1Corinthians', '1Cor',
    '2 Corinthians', '2 Cor', '2Corinthians', '2Cor',
    'Galatians',  'Gal',
    'Ephesians',  'Eph',
    'Philippians', 'Phil',
    'Colossians', 'Col',
    '1 Thessalonians', '1 Thess', '1Thessalonians', '1Thess',
    '2 Thessalonians', '2 Thess', '2Thessalonians', '2Thess',
    '1 Timothy', '1 Tim', '1Timothy', '1Tim',
    '2 Timothy', '2 Tim', '2Timothy', '2Tim',
    'Titus',
    'Philemon', 'Phlm',
    'Hebrews', 'Heb',
    'James',  'Jas',
    '1 Peter', '1 Pet',  '1Peter', '1Pet',
    '2 Peter', '2 Pet',  '2Peter', '2Pet',
    '1 John',  '1 John', '1John',  '1John',
    '2 John',  '2 John', '2John',  '2John',
    '3 John',  '3 John', '3John',  '3John',
    'Jude',
    'Revelation', 'Rev', 'Apocalypse', 'Apoc'

    # Apocrypha
    'Tobit', 'Tobias', 'Tob',
    'Judith', 'Jdt',
    'Wisdom of Solomon', 'Wisdom', 'Wisd',
    'Sirach', 'Sir', 'Ecclesiasticus'
    'Baruch',
    'Letter of Jeremiah', 'Epistle of Jeremiah',
    'Prayer of Azariah', 'Song of the Three Children', 'Azariah'
    '1 Maccabees', '1 Mac', '1Maccabees', '1Macc',
    '2 Maccabees', '2 Mac', '2Maccabees', '2Macc',
    '3 Maccabees', '3 Mac', '3Maccabees', '3Macc',
    '4 Maccabees', '4 Mac', '4Maccabees', '4Macc',
    'Prayer of Manasseh', 'Manasseh',
]